' Gambas module file

Public Function contiene(texto As String, textoabuscar As String) As Boolean '' devuelve verdadero o falso si un texto contiene textoabuscar

    If String.InStr(texto, textoabuscar) <> 0 Then
        Return True
    Else
        Return False
    Endif

End

Public Function DefinirGridSinFormato(OrigenGrid As Gridview, contenido As String)

    Dim a, b As Integer
    Dim lineas As String[]
    Dim columnas As String[]

    '1º fase: estudia contenido
    lineas = Split(contenido, "\n") 'separadas por salto de linea

    'la primera linea tiene los datos de nombre de columnas
    columnas = Split(lineas[0], "\t") 'separadas por tabulador

    'para borrar todo el contenido....
    OrigenGrid.Clear()

    'defino grid
    With OrigenGrid
        .header = 3
        .columns.count = columnas.Count
        .rows.count = lineas.count - 1 'le quito la primera linea

        For a = 0 To columnas.count - 1
            .columns[a].title = columnas[a]
        Next

        .Font.name = "Sans"
        .Font.size = 8
        .Mode = Select.Single
    End With

    'ahora meto los datos en las filas por cada columna

    For a = 1 To lineas.count - 1
        columnas = Split(lineas[a], "\t")
        For b = 0 To columnas.count - 1

            Try OrigenGrid[a - 1, b].text = columnas[b]

        Next

    Next

    Return

End

Public Function DefinirGrid(OrigenGrid As Gridview, contenido As String, Optional datosApuestas As Integer)

    Dim a, b As Integer
    Dim lineas As String[]
    Dim columnas As String[]

    '1º fase: estudia contenido
    lineas = Split(contenido, "\n") 'separadas por salto de linea

    'la primera linea tiene los datos de nombre de columnas
    columnas = Split(lineas[0], "\t") 'separadas por tabulador

    'para borrar todo el contenido....
    OrigenGrid.Clear()

    'defino grid

    With OrigenGrid
        .header = 3
        .columns.count = columnas.Count
        .rows.count = lineas.count - 1 'le quito la primera linea

        For a = 0 To columnas.count - 1
            .columns[a].title = columnas[a]
        Next

        .Font.name = "Sans"
        .Font.size = 8
        .Mode = Select.Single
    End With

    'ahora meto los datos en las filas por cada columna

    For a = 1 To lineas.count - 1
        columnas = Split(lineas[a], "\t")
        For b = 0 To columnas.count - 1

            ' If datosApuestas = True Then
            If b > 0 And InStr(columnas[b], "/") = 0 Then
                Try OrigenGrid[a - 1, b].text = Format(Val(columnas[b]), "0.#0")
                Try OrigenGrid[a - 1, b].Alignment = Align.Right
            Else
                Try OrigenGrid[a - 1, b].text = columnas[b]
            Endif
            ' Else
            '
            '     Try OrigenGrid[a - 1, b].text = columnas[b]
            ' Endif
            If datosApuestas = 3 Then
                'caso en que son resumenen
                Try OrigenGrid[a - 1, b].text = columnas[b]

            Endif

        Next

    Next

    Return

End

Public Sub vaciarDirectorio(ruta As String, Optional patron As String) ''Borrar contenido de un directorio dado un patron de borrado
    'borrado si existe la ruta

    Dim file As String

    If patron = "" Then patron = "*"
    If Exist(ruta) Then
        For Each File In Dir(ruta & "/", patron)
            Try Kill ruta & "/" & file
        Next
    Endif
Catch
    Message.Error(("Error al intentar borrar el directorio: ") & ruta)

End

Public Sub ColorCeldaNumeroNegativo(g As GridView, c As Integer)

    Dim a As Integer

    'por defecto:

    For a = 0 To g.rows.Count - 1
        ' g[a, c].Foreground = Color.black
        If Not g[a, c].text = "" And If Val(g[a, c].text) < 0 Then
            g[a, c].Foreground = Color.Red
        Endif

    Next

End

Public Function Between(Datos As String, Cadena1 As String, Cadena2 As String) As String

    Dim iinf As Integer
    Dim isup As Integer

    iinf = InStr(Datos, Cadena1) + Len(Cadena1)
    isup = InStr(Datos, Cadena2, iinf)
    Return Mid(Datos, iinf, isup - iinf)

End

Public Function PonerIconoFechaActual(G As GridView, columna As Integer)

    Dim a As Integer
    Dim fechaActual As String
    Dim fechaDiaAnterior As String

    'por defecto:
    fechaActual = Format$(Now, "dd")
    fechaActual &= "/" & Format$(Now, "mm")
    fechaActual &= "/" & Format$(Now, "yyyy")
    'fecha dia anterior
    fechaDiaAnterior = Format$(DateAdd(Now, gb.day, -1), "dd")
    fechaDiaAnterior &= "/" & Format$(DateAdd(Now, gb.day, -1), "mm")
    fechaDiaAnterior &= "/" & Format$(DateAdd(Now, gb.day, -1), "yyyy")

    For a = 0 To g.rows.Count - 1
        If g[a, 3].text = fechaActual Then
            g[a, 0].picture = Picture["exclamacion20x20.png"]
        Endif
        If g[a, 3].text = fechaDiaAnterior Then
            g[a, 0].picture = Picture["Icono_alarmaTriangulo20x20.jpg"]
        Endif

    Next

End

Public Function abrirIdApuesta(idapuesta As String)

    Dim textobusqueda As String
    Dim encontrada As New String[]
    Dim arrayfichero As String[]
    Dim nombrefile As String
    Dim rutabusqueda As String = Settings["rutaDirectorio", "/home/hdd/mint/Documentos/00 analisis apuestas"]

    If Len(idapuesta) = 5 Then
        TextoBusqueda = Mid$(idapuesta, 1, 2) & " " & Mid$(idapuesta, 3, 5)
    Else
        If InStr(idapuesta, "-") = 0 Then
            TextoBusqueda = Mid$(idapuesta, 1, 6) 'limito la busqueda hasta el sexto caracter
        Else
            TextoBusqueda = Mid$(idapuesta, 1, InStr(idapuesta, "-") - 1) 'limito la busqueda hasta el "-" en el nombre
            If Len(TextoBusqueda) = 5 Then
                TextoBusqueda = Mid$(TextoBusqueda, 1, 2) & " " & Mid$(TextoBusqueda, 3, 5)
            Endif
        Endif

    Endif

    arrayfichero = Dir(rutaBusqueda, "*" & TextoBusqueda & "*", gb.File)
    For Each nombrefile In arrayfichero
        encontrada.add(nombrefile)

    Next

    For Each nombrefile In encontrada
        If InStr(nombrefile, "lock") = 0 Then
            'lo puedo abrir
            Desktop.Open(rutabusqueda & "/" & nombrefile)

            Break ''solo abrir el primero
        Endif
    Next

End

'----------------------------------------------------------------------------
Public Function BorraLinea(lineas As String[], l As String) '''borra una linea del array Lineas que sea igual a la dada "l"

    Dim a As Integer

    For a = 0 To lineas.count - 1
        If lineas[a] = l Then
            lineas.Delete(a)
            Return
        Endif
    Next

End

Public Function valorar(l As String) As Float ''quita espacio, signo de moneda y convierte de punto a coma el texto dado para devolver un numero

    Dim valor As Float

    l = Replace(l, " ", "")
    l = Replace(l, "€", "")
    l = Replace(l, ".", ",")
    Try valor = Val(l) 'prueba por si hay un error
    If Error Then

        Return 0
    Endif
    Return Val(l)

End

Public Function similar(casa As String) As String

    casa = Lower(casa)

    If casa = "" Then
        Message.Info("Error: falta definir casa de apuesta")
        Return "ERROR_CASA"
        Return ""
    Endif

    If contiene(casa, "winama") Then Return "winamax"

    If contiene(casa, "Sisa") Then Return "sisal"
    If contiene(casa, "mrgre") Then Return "mrgreen"

    If contiene(casa, "vers") Then Return "versus"
    If contiene(casa, "sus") Then Return "versus"

    If contiene(casa, "gging") Then Return "juegging"
    If contiene(casa, "jueg") Then Return "juegging"

    If contiene(casa, "fai") Then Return "betfair"

    If contiene(casa, "77") Then Return "777"
    If contiene(casa, "leo") Then Return "leovegas"
    If contiene(casa, "ovega") Then Return "leovegas"
    If contiene(casa, "starve") Then Return "admiralbet"
    If contiene(casa, "arvega") Then Return "admiralbet"
    If contiene(casa, "admiral") Then Return "admiralbet"

    If contiene(casa, "mondo") Then Return "mondobets"
    If contiene(casa, "mon") Then Return "mondobets"
    If contiene(casa, "mondobet") Then Return "mondobets"

    If contiene(casa, "racha") Then Return "enracha"
    If contiene(casa, "enra") Then Return "enracha"

    If contiene(casa, "way") Then Return "betway"
    If contiene(casa, "betway") Then Return "betway"
    If contiene(casa, "betw") Then Return "betway"

    If contiene(casa, "pas") Then Return "paston"
    If contiene(casa, "paston") Then Return "paston"
    If contiene(casa, "tón") Then Return "paston"
    If Len(casa) = 1 And casa = "p" Then Return "paston" '

    If contiene(casa, "f") Then Return "paf"
    If contiene(casa, "uni") Then Return "paf" 'unibet

    If contiene(casa, "co") Then Return "codere"

    If contiene(casa, "ci") Then Return "circus"
    If contiene(casa, "cu") Then Return "circus"
    If contiene(casa, "circu") Then Return "circus"

    If contiene(casa, "go") Then Return "goldenpark"

    If contiene(casa, "8") Then Return "888"

    If contiene(casa, "bw") Then Return "bwin"

    If contiene(casa, "wi") Then Return "williamhill"
    If contiene(casa, "w ") Then Return "williamhill"

    If contiene(casa, "w+c") Then Return "williamhill"
    If contiene(casa, "w.c") Then Return "williamhill"
    If contiene(casa, "wc") Then Return "williamhill"

    If contiene(casa, "wan") Then Return "wanabet"

    If contiene(casa, "lu") Then Return "luckia"
    If contiene(casa, "ck") Then Return "luckia"
    If contiene(casa, "10") Then Return "luckia" '10bet

    If contiene(casa, "sp") Then Return "sportium"
    If contiene(casa, "lad") Then Return "sportium" 'ladbrokes

    If contiene(casa, "mb") Then Return "mbet"
    If contiene(casa, "mat") Then Return "mbet"
    If contiene(casa, "tho") Then Return "mbet"
    If contiene(casa, "mara") Then Return "mbet"
    If contiene(casa, "met") Then Return "mbet"

    If contiene(casa, "3") Then Return "bet365"
    If contiene(casa, "6") Then Return "bet365"
    If contiene(casa, "5") Then Return "bet365"

    If contiene(casa, "88") Then Return "888sport"
    If contiene(casa, "8s") Then Return "888sport"

    If contiene(casa, "betsta") Then Return "betstars"
    If contiene(casa, "st") Then Return "betstars"
    If contiene(casa, "tar") Then Return "betstars"
    If contiene(casa, "poke") Then Return "betstars"

    If Len(casa) = 1 And casa = "w" Then Return "williamhill" 'por defecto si es de longitud 1 caracter, y si es w ponew willianhilll

    '  If contiene(casa, "casa") Then
    Message.Error("Casa de apuesta no indicada correctamente: " & CASA)
    Return "ERROR_CASA"
    '

End
